In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("C:\\Users\\raghu\\Downloads\\GYM.csv")

In [3]:
data.head()

number_people  day_of_week  is_weekend  is_holiday  temperature  \
0             37            4           0           0        71.76   
1             45            4           0           0        71.76   
2             40            4           0           0        71.76   
3             44            4           0           0        71.76   
4             45            4           0           0        71.76   

   is_start_of_semester  is_during_semester  month  hour  
0                     0                   0      8    17  
1                     0                   0      8    17  
2                     0                   0      8    17  
3                     0                   0      8    17  
4                     0                   0      8    17

In [4]:
data.isnull().sum()

number_people           0
day_of_week             0
is_weekend              0
is_holiday              0
temperature             0
is_start_of_semester    0
is_during_semester      0
month                   0
hour                    0
dtype: int64

In [5]:
data.duplicated().sum()

14218

In [6]:
data.shape

(62184, 9)

In [7]:
data.drop_duplicates(inplace=True)

In [8]:
data.shape

(47966, 9)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

C:\Users\raghu\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.25.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [10]:
import warnings
warnings.filterwarnings('ignore')

In [11]:
x=data.drop("hour",axis=1)

In [12]:
x_scaled=scaler.fit_transform(x)
x_scaled

array([[ 0.15488137,  0.55469165, -0.59563445, ..., -0.3064561 ,
        -1.50439861,  0.19901159],
       [ 0.52504011,  0.55469165, -0.59563445, ..., -0.3064561 ,
        -1.50439861,  0.19901159],
       [ 0.29369089,  0.55469165, -0.59563445, ..., -0.3064561 ,
        -1.50439861,  0.19901159],
       ...,
       [-0.40035674,  1.06109324,  1.67888207, ..., -0.3064561 ,
         0.66471744, -1.24666308],
       [-0.72424564,  1.06109324,  1.67888207, ..., -0.3064561 ,
         0.66471744, -1.24666308],
       [-0.49289643,  1.06109324,  1.67888207, ..., -0.3064561 ,
         0.66471744, -1.24666308]])

In [21]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)

In [22]:
pca_data=pca.fit_transform(x_scaled)

In [31]:
pca_data

array([[-0.03746957, -0.21907648],
       [ 0.10292297, -0.38866629],
       [ 0.01517764, -0.28267266],
       ...,
       [-1.77621089, -0.61707962],
       [-1.89905437, -0.46868853],
       [-1.81130903, -0.57468216]])

In [25]:
x_scaled_back=pca.inverse_transform(pca_data)

In [28]:
x_scaled_back.shape

(47966, 8)

In [30]:
import numpy as np
ov=np.var(x_scaled,axis=0).sum()
ov

8.0

In [33]:
reconstructed_variance = np.var(x_scaled_back, axis=0).sum()

In [34]:
reconstructed_variance

3.481164219258442

In [35]:
8-3.481164219258442

4.518835780741558

In [36]:
ov=np.var(pca_data,axis=0).sum()

In [37]:
ov

3.481164219258439

In [38]:
data.corr()

number_people  day_of_week  is_weekend  is_holiday  \
number_people              1.000000    -0.146298   -0.150431   -0.042411   
day_of_week               -0.146298     1.000000    0.780353   -0.063419   
is_weekend                -0.150431     0.780353    1.000000   -0.025681   
is_holiday                -0.042411    -0.063419   -0.025681    1.000000   
temperature                0.323779     0.028941    0.042101   -0.075868   
is_start_of_semester       0.190029    -0.007247   -0.011238   -0.013213   
is_during_semester         0.332529    -0.006748   -0.034841   -0.064863   
month                     -0.065366     0.005173    0.003287   -0.078683   
hour                       0.486666     0.041358    0.056542    0.010841   

                      temperature  is_start_of_semester  is_during_semester  \
number_people            0.323779              0.190029            0.332529   
day_of_week              0.028941             -0.007247           -0.006748   
is_weekend               0.042101             -0.011238           -0.034841   
is_holiday              -0.075868             -0.013213           -0.064863   
temperature              1.000000              0.084437            0.113565   
is_start_of_semester     0.084437              1.000000            0.203707   
is_during_semester       0.113565              0.203707            1.000000   
month                    0.120793             -0.140239            0.107893   
hour                     0.146436             -0.001930            0.009605   

                         month      hour  
number_people        -0.065366  0.486666  
day_of_week           0.005173  0.041358  
is_weekend            0.003287  0.056542  
is_holiday           -0.078683  0.010841  
temperature           0.120793  0.146436  
is_start_of_semester -0.140239 -0.001930  
is_during_semester    0.107893  0.009605  
month                 1.000000 -0.010255  
hour                 -0.010255  1.000000

In [42]:
min_correlation = data.corr().unstack().sort_values().iloc[0]

print(f"Minimum correlation: {min_correlation}")

Minimum correlation: -0.15043076822928994


In [48]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Load the dataset
data = pd.read_csv("C:\\Users\\raghu\\Downloads\\GYM.csv")

# Assume the target column (if any) is excluded from the data
X = data.drop(columns=['hour'])  # Modify this as per your dataset

# Standardize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA
pca = PCA(n_components=0.99)
pca.fit(X_scaled)

# Get the explained variance (eigenvalues)
eigenvalues = pca.explained_variance_

# Calculate the sum of the first 8 eigenvalues
sum_eigenvalues_first_8 = eigenvalues[:8].sum()

print(f"Sum of eigenvalues for the first 8 components: {sum_eigenvalues_first_8}")


Sum of eigenvalues for the first 8 components: 8.000128652525607


In [49]:
eigenvalues

array([1.92509186, 1.62554618, 1.16810664, 0.92875016, 0.91149889,
       0.73610627, 0.49834257, 0.20668608])

In [51]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

# Load the dataset
data = pd.read_csv("C:\\Users\\raghu\\Downloads\\GYM.csv")
# data.drop_duplicates(inplace=True)

# Assume the target column (if any) is named 'target'
X = data.drop(columns=['hour'])  # Features
y = data['hour']  # Target

# Standardize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=24)

# Model 1: Linear Regression on raw data
model1 = LinearRegression()
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)
rmse1 = np.sqrt(mean_squared_error(y_test, y_pred1))

# Apply PCA with n_components=4
pca = PCA(n_components=4)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

# Model 2: Linear Regression on PCA-transformed data
model2 = LinearRegression()
model2.fit(X_train_pca, y_train)
y_pred2 = model2.predict(X_test_pca)
rmse2 = np.sqrt(mean_squared_error(y_test, y_pred2))

# Print RMSE values and compare
print(f"RMSE for Model 1 (raw data): {rmse1}")
print(f"RMSE for Model 2 (PCA-transformed data): {rmse2}")

# Compare performance
if rmse2 < rmse1:
    print("Model 2 performance is better than Model 1")
elif rmse2 == rmse1:
    print("No change in performance")
else:
    print("Model 2 performance is not better than Model 1")


RMSE for Model 1 (raw data): 5.439104717333018
RMSE for Model 2 (PCA-transformed data): 6.142322771399546
Model 2 performance is not better than Model 1


In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

# Load the dataset
data = pd.read_csv("C:\\Users\\raghu\\Downloads\\GYM.csv")

# Assume the target column (if any) is named 'target'
X = data.drop(columns=['hour'])  # Features
y = data['hour']  # Target

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=24)

# Model 1: Linear Regression on raw data
model1 = LinearRegression()
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)
rmse1 = np.sqrt(mean_squared_error(y_test, y_pred1))

# Apply StandardScaler and PCA with n_components=4
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

pca = PCA(n_components=4)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

# Model 2: Linear Regression on PCA-transformed data
model2 = LinearRegression()
model2.fit(X_train_pca, y_train)
y_pred2 = model2.predict(X_test_pca)
rmse2 = np.sqrt(mean_squared_error(y_test, y_pred2))

# Print RMSE values and compare
print(f"RMSE for Model 1 (raw data): {rmse1}")
print(f"RMSE for Model 2 (StandardScaler & PCA-transformed data): {rmse2}")

# Compare performance
if rmse2 < rmse1:
    print("Model 2 performance is better than Model 1")
elif rmse2 == rmse1:
    print("No change in performance")
else:
    print("Model 2 performance is not better than Model 1")


RMSE for Model 1 (raw data): 5.439104717333018
RMSE for Model 2 (StandardScaler & PCA-transformed data): 6.201957223070592
Model 2 performance is not better than Model 1
